---
name: Bio-NEXUS-Import
version: 0.1.0
author:
  - 'Markus Riester <mriester@gmx.de>'
abstract: |-
  Extends Bio::NEXUS with parsers for file formats of
  popular phylogeny programs
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Bio::NEXUS: 0.67
  perl: 5.6.1
  version: 0
build_requires:
  Test::More: 0
provides:
  Bio::NEXUS::Import:
    file: lib/Bio/NEXUS/Import.pm
    version: 0.1.0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
