# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bio-NEXUS-Import
version:      v0.0.2
version_from: lib/Bio/NEXUS/Import.pm
installdirs:  site
requires:
    Bio::NEXUS:                    0.67
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
